name: Build and Push Frontend Image

on:
  push:
    branches:
      - main
    paths:
      - 'IzvorniKod/React/**'      # Trigger only on changes in the /IzvorniKod/React directory
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      FRONTEND_DEPLOY_HOOK: ${{ secrets.FRONTEND_DEPLOY_HOOK }}

    steps:
      - name: set lower case repository names
        run: |
          echo "REPO_LC=${REPO,,}" >> ${GITHUB_ENV}
        env:
          REPO: '${{ github.event.repository.name }}'
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./IzvorniKod/React
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}/izvornikod/react:latest

      - name: Trigger release
        if: ${{ env.FRONTEND_DEPLOY_HOOK }}
        run: curl ${{ env.FRONTEND_DEPLOY_HOOK }}
