name: Build and Push Backend Image

on:
  push:
    branches:
      - main
    paths:
      - 'IzvorniKod/ppdadel-spring/**'      # Trigger only on changes in the /backend directory
  workflow_dispatch:

jobs:
  build-and-push-backend:
    name: Build and Push Backend
    runs-on: ubuntu-latest
    env:
      BACKEND_DEPLOY_HOOK: ${{ secrets.BACKEND_DEPLOY_HOOK }}

    steps:
      - name: set lower case repository names
        run: |
          echo "REPO_LC=${REPO,,}" >> ${GITHUB_ENV}
        env:
          REPO: '${{ github.event.repository.name }}'
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Add this
      - id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          context: ./IzvorniKod/ppdadel-spring
          push: true

      - name: Trigger release
        if: ${{ env.BACKEND_DEPLOY_HOOK }}
        run: curl ${{ env.BACKEND_DEPLOY_HOOK }}
