name: Build and Push Backend Image

on:
  push:
    branches:
      - main
    paths:
      - 'IzvorniKod/ppdadel-spring/**'      # Trigger only on changes in the /backend directory
  workflow_dispatch:

jobs:
  build-and-push-backend:
    name: Build and Push Backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      BACKEND_DEPLOY_HOOK: ${{ secrets.BACKEND_DEPLOY_HOOK }}

    steps:
      - name: set lower case repository names
        run: |
          echo "REPO_LC=${REPO,,}" >> ${GITHUB_ENV}
        env:
          REPO: '${{ github.event.repository.name }}'
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
          cache-dependency-path: 'IzvorniKod/ppadel-spring/pom.xml'
          
      - name: Maven build
        run: mvn clean package
        working-directory: IzvorniKod/ppadel-spring

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Add this
      - id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./IzvorniKod/ppadel-spring
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}/izvornikod/ppadel-spring:latest

      - name: Trigger release
        if: ${{ env.BACKEND_DEPLOY_HOOK }}
        run: curl ${{ env.BACKEND_DEPLOY_HOOK }}
